version: "3"

services:
    web:
        build: .
        ports:
            - "8200:8000"
        volumes:
            - .:/app
    client:
        image: nginx
        ports:
            - 8100:80
        volumes:
            - .:/usr/share/nginx/html
